version: '2'
services:
    django:
        environment:
            DJANGO_SETTINGS_MODULE: home.settings.dev

    react:
        volumes:
            - ./react:/srv/react
        ports:
            - "3000:3000"
