version: '2'
services:
    django:
        volumes:
            - ./django/src:/srv/django
        environment:
            DJANGO_SETTINGS_MODULE: home.settings.dev

    nginx:
        ports:
            - "8080:80"

    react:
        volumes:
            - ./react:/srv/react
        ports:
            - "3000:3000"
        links:
            - nginx:nginx
    db:
        expose:
            - "3306"