version: '2'
services:
    django:
        extends:
            file: common.yml
            service: django
        ports:
            - "8000:8000"
        volumes:
            - ./media:/srv/django/template/media
            - react_build:/srv/django/template
        network_mode: "host"

    nginx:
        image: nginx:latest
        container_name: ng
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./nginx/config/:/etc/nginx/conf.d
        depends_on:
            - django

    react:
        build: ./react
        volumes:
            - react_build:/srv/react/build

volumes:
    react_build: {}
    media: {}
